This notebook is used to extractor the necessary data for Salary Prediction from 2017 Stack Overflow Annual Developer Survey 

https://insights.stackoverflow.com/survey

In [1]:
import pandas as pd
import numpy as np

NOTE: Make sure **Data/source/** folder has the survey data downloaded using **Scripts/download_survey_data.py --all** script

### 2017 Stack Overflow User Survey

In [2]:
survey_res = pd.read_csv("../Data/source/2017.csv", sep=",", encoding='Latin-1', low_memory=False)

In [3]:
print(f"Number of responses to the survey in 2017: {survey_res.shape[0]}")

Number of responses to the survey in 2017: 51392

In [4]:
survey_res.head()

,Respondent,Professional,ProgramHobby,Country,University,EmploymentStatus,FormalEducation,MajorUndergrad,HomeRemote,CompanySize,...,StackOverflowMakeMoney,Gender,HighestEducationParents,Race,SurveyLong,QuestionsInteresting,QuestionsConfusing,InterestedAnswers,Salary,ExpectedSalary
0,1,Student,"Yes, both",United States,No,"Not employed, and not looking for work",Secondary school,NaN,NaN,NaN,...,Strongly disagree,Male,High school,White or of European descent,Strongly disagree,Strongly agree,Disagree,Strongly agree,NaN,NaN
1,2,Student,"Yes, both",United Kingdom,"Yes, full-time",Employed part-time,Some college/university study without earning ...,Computer science or software engineering,"More than half, but not all, the time",20 to 99 employees,...,Strongly disagree,Male,A master's degree,White or of European descent,Somewhat agree,Somewhat agree,Disagree,Strongly agree,NaN,37500.0
2,3,Professional developer,"Yes, both",United Kingdom,No,Employed full-time,Bachelor's degree,Computer science or software engineering,"Less than half the time, but at least one day ...","10,000 or more employees",...,Disagree,Male,A professional degree,White or of European descent,Somewhat agree,Agree,Disagree,Agree,113750.0,NaN
3,4,Professional non-developer who sometimes write...,"Yes, both",United States,No,Employed full-time,Doctoral degree,A non-computer-focused engineering discipline,"Less than half the time, but at least one day ...","10,000 or more employees",...,Disagree,Male,A doctoral degree,White or of European descent,Agree,Agree,Somewhat agree,Strongly agree,NaN,NaN
4,5,Professional developer,"Yes, I program as a hobby",Switzerland,No,Employed full-time,Master's degree,Computer science or software engineering,Never,10 to 19 employees,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Extract the Country 
survey_res_flt = pd.DataFrame()
survey_res_flt["country"] = survey_res["Country"]

# Extract student information 
survey_res_flt["student"] = survey_res["Professional"]

# Extract employment status
survey_res_flt["employment_status"] = survey_res["EmploymentStatus"]

# Extract employment status
survey_res_flt["formal_education"] = survey_res["FormalEducation"]

# Extract company size ~ Number of developers
survey_res_flt["company_size"] = survey_res["CompanySize"]

# Extract occupation 
survey_res_flt["occupation"] = survey_res["DeveloperType"]

# Extract years of IT/programing experience
survey_res_flt["IT_experience_in_years"] = survey_res["YearsProgram"]

# Extract years of IT/programing experience in Job
survey_res_flt["IT_experience_in_years_job"] = survey_res["YearsCodedJob"]

# Extract job satisfaction 
survey_res_flt["job_satisfaction"] = survey_res["JobSatisfaction"]

# Extract compensation
survey_res_flt["compensation"] = survey_res["Salary"]

# Extract programming language/technology 
survey_res_flt["proficient_languages"] = survey_res["HaveWorkedLanguage"].apply(lambda x: x.split(";") if not isinstance(x, float) else x)

# Extract programming language/technology 
survey_res_flt["database_worked_on"] = survey_res["HaveWorkedDatabase"].apply(lambda x: x.split(";") if not isinstance(x, float) else x)

# Extract programming language/technology 
survey_res_flt["platform_worked_on"] = survey_res["HaveWorkedPlatform"].apply(lambda x: x.split(";") if not isinstance(x, float) else x)

# Extract programming language/technology 
survey_res_flt["framework_worked_on"] = survey_res["HaveWorkedFramework"].apply(lambda x: x.split(";") if not isinstance(x, float) else x)


# Extract time spent on work 
survey_res_flt["work_hours_week"] = survey_res["HoursPerWeek"]

#Extract gender
survey_res_flt["gender"] = survey_res["Gender"]

In [8]:
survey_res_flt.head()

,country,student,employment_status,formal_education,company_size,occupation,IT_experience_in_years,IT_experience_in_years_job,job_satisfaction,compensation,proficient_languages,database_worked_on,platform_worked_on,framework_worked_on,work_hours_week,gender
0,United States,Student,"Not employed, and not looking for work",Secondary school,NaN,NaN,2 to 3 years,NaN,NaN,NaN,[Swift],NaN,[iOS],NaN,0.0,Male
1,United Kingdom,Student,Employed part-time,Some college/university study without earning ...,20 to 99 employees,NaN,9 to 10 years,NaN,NaN,NaN,"[JavaScript, Python, Ruby, SQL]","[MySQL, SQLite]",[Amazon Web Services (AWS)],[.NET Core],NaN,Male
2,United Kingdom,Professional developer,Employed full-time,Bachelor's degree,"10,000 or more employees",Other,20 or more years,20 or more years,9.0,113750.0,"[Java, PHP, Python]",[MySQL],NaN,NaN,NaN,Male
3,United States,Professional non-developer who sometimes write...,Employed full-time,Doctoral degree,"10,000 or more employees",NaN,14 to 15 years,9 to 10 years,3.0,NaN,"[Matlab, Python, R, SQL]","[MongoDB, Redis, SQL Server, MySQL, SQLite]","[Windows Desktop, Linux Desktop, Mac OS, Am...",[React],5.0,Male
4,Switzerland,Professional developer,Employed full-time,Master's degree,10 to 19 employees,Mobile developer; Graphics programming; Deskto...,20 or more years,10 to 11 years,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
survey_res_flt.to_csv("../Data/filtered/2017.csv", index=False)